#!/usr/bin/env python3

import subprocess
import sys

SSID_LOCATION_MAP = {"Noisebridge Cap": "Noisebridge"}


def getSSID():
    result = subprocess.run(["ipconfig", "getsummary", "en0"],
                            capture_output=True,
                            text=True,
                            check=True)

    for line in result.stdout.split('\n'):
        if ' SSID' in line:
            ssid = line.split(':', 1)[1].strip()
            return ssid
    print("authored-at: Couldn't get SSID.")
    return None


def addAuthoredAt(msgFile, location):
    with open(msgFile, 'a') as f:
        f.write(f"\nAuthored-at: {location}\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(1)

    msgFile = sys.argv[1]

    ssid = getSSID()

    if ssid and ssid in SSID_LOCATION_MAP:
        location = SSID_LOCATION_MAP[ssid]
        addAuthoredAt(msgFile, location)

    sys.exit(0)
